### ISSUE TITLE
[Suggestion] Make the entropy endstone islands spawn in the End only

### ISSUE THREAD

**Issue by V-Boy** [EleC0TroN/ER#1]
They look out of place in the overworld, and I think they would look far better in the End. They also make getting ender pearls far too easy.

**Comment by EleC0TroN** [comment]
This is part of the early progress in the mod. You can turn off islands in the config.

**Comment by V-Boy** [comment]
Sorry if you don’t mind me asking, but what is the entropy endstone stuff used for? I couldn’t find a use for it in JEI

On Apr 2, 2020, at 4:20 AM, EleC0TroN <notifications@github.com<mailto:notifications@github.com>> wrote:


This is part of the early progress in the mod. You can turn off islands in the config.

**Comment by EleC0TroN** [comment]
> Sorry if you don’t mind me asking, but what is the entropy endstone stuff used for? I couldn’t find a use for it in JEI

Entropy End Stone is useless in recipes. This block is only needed so that the player does not have too much access to the End Stone in Overworld.
