### ISSUE TITLE
Materializer crash end reborn 0.3.8 with forge 14.23.5.2854

### ISSUE THREAD

**Issue by brotherrick** [EleC0TroN/ER#10]
[crash-2020-06-29_19.12.10-client.txt](https://github.com/EleC0TroN/ER/files/4851376/crash-2020-06-29_19.12.10-client.txt)

When i try to put an item in the materializer i always get this error and im not competent enough to understand what is causing it.

**Comment by EleC0TroN** [comment]
Can you check if the error is repeated in one world or always? I now tried to run with these mods, but there no error. You can also try to delete the mod config file

**Comment by EleC0TroN** [comment]
This is version 0.3.8 with the old materializer system. Maybe it will work normally

[EndReborn[0.3.8]S.zip](https://github.com/EleC0TroN/ER/files/4857600/EndReborn.0.3.8.S.zip)

**Comment by brotherrick** [comment]
Well i tried the two things above and it didnt work. However the zip file with the old system did work well. I must also say that with both versions my materializer has the same gui and the same look and maybe its not normal? What is different between the two?

**Comment by EleC0TroN** [comment]
In the version from the archive materializer uses simple items in recipes. Normal version - Ore dictionary items, that can be changed in the config file.
Well, is problem solved?

**Comment by brotherrick** [comment]
yes it works with the special version for me
