### ISSUE TITLE
[BUG] Xorcite infinite XP

### ISSUE THREAD

**Issue by CalaMariGold** [EleC0TroN/ER#11]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/424

1.12.2

**Comment by EleC0TroN** [comment]
I will try to fix it in the next update. Thanks for feedback

**Comment by CalaMariGold** [comment]
This is still an issue on the newest End Reborn version.

**Comment by democat3457** [comment]
This is still an issue @EleC0TroN

**Comment by democat3457** [comment]
Still an issue in 0.3.9. See linked issue above
