### ISSUE TITLE
[1.15.2] Sledgehammer dupe when repairing itself.

### ISSUE THREAD

**Issue by Kai-Kramer** [EleC0TroN/ER#15]
By repairing sledgehammers (the vanilla way) you can dupe sledgehammers to your heart's content. This is problematic with any mod that has un-crafting or tool smelting into ingots/molten metal.

Mod list:
Astral sorcery (+ lib)
Immersive Engineering
Baubles
End:Reborn

Steps to reproduce:
[Crafting screenshot 1](https://prnt.sc/tx2wyi)
[Crafting screenshot 2](https://prnt.sc/tx2x70)
[Crafting screenshot 3](https://prnt.sc/tx2xbl)

**Comment by EleC0TroN** [comment]
I`ll try to fix this in the next update. Thanks for feedback
