### ISSUE TITLE
Insta-crash upon startup.

### ISSUE THREAD

**Issue by EnderBro123** [EleC0TroN/ER#2]
https://www.dropbox.com/s/4w3j9j4s5f2duyl/crash-2020-04-04_13.30.07-server.txt?dl=0
Mods listed in the file.

**Comment by EleC0TroN** [comment]
It caused by conflict with RandomPatches mod. With Optifine there no error, how i can see.

**Comment by EleC0TroN** [comment]
Has any modpack been used?

**Comment by EnderBro123** [comment]
@EleC0TroN 

Well, game insta-crashes on 0.3.2 so.
