### ISSUE TITLE
A few typos (Trying to help. Ik your not English. ;) )

### ISSUE THREAD

**Issue by EnderBro123** [EleC0TroN/ER#3]
Metal* It could be Molten Enderium tbf but eh.
![2020-04-05_08 32 00](https://user-images.githubusercontent.com/51277766/78502843-fd8c3980-7717-11ea-9686-3680bd36bb48.png)

For the Runic Block, I tried putting 8 purpur blocks around it. Notning. 8 Purple wool, nothing. How is this used?
![2020-04-05_08 33 22](https://user-images.githubusercontent.com/51277766/78502883-388e6d00-7718-11ea-9fe9-e813581f12ac.png)

Appears in the Nether*
![2020-04-05_08 34 32](https://user-images.githubusercontent.com/51277766/78502894-4ba13d00-7718-11ea-917a-365ef9bc0b04.png)
![2020-04-05_15 15 09](https://user-images.githubusercontent.com/51277766/78511289-511a7980-7750-11ea-85b6-691442c6059f.png)

A Chorus Fruit alternative*
![2020-04-05_08 37 39](https://user-images.githubusercontent.com/51277766/78502982-b94d6900-7718-11ea-8e09-80d240817047.png)

Also, I don't think the Void Forge is needed since it only has one use now, so instead you could simply throw Endorium Ingots into lava or on top of magma, and it'd poop out the Molten Endorium.

**Comment by EleC0TroN** [comment]
Yes, thanks. In next "fix-update" on 1.12.2 it will be fix. And about Void Forge... it`s still in mod just for a change.

**Comment by EnderBro123** [comment]
Oh, You took a bit to respond lol.

**Comment by EleC0TroN** [comment]
And about boss summoning. Runic Block must be placed last of all. Sorry if you had to wait a long time for a reply.

**Comment by EnderBro123** [comment]
Oh, you might wanna add that info to the lore.
