### ISSUE TITLE
[BUG] Ender's Flower- Infinite Source of XP

### ISSUE THREAD

**Issue by kil0byt3** [EleC0TroN/ER#4]
Please see below for info.

https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/119

**Comment by EleC0TroN** [comment]
Hmm, it seems like a conflict with the Quark mod(or Pam`s Harvestcraft), which allows you to harvest with right click. By default, right click harvest is not works on the Ender Flower(with those mods). So you can check the configs:
Quark; Tweaks/Right click harvest/config. And check if there are line "endreborn:crop_ender_flower"
HarvestCraft: config/harvestcraft. And check "B:enableEasyHarvest=true"

**Comment by EleC0TroN** [comment]
Will be fixed in the next fix-update on 1.12.2
