### ISSUE TITLE
0.5.5 End Biome Generation Bug

### ISSUE THREAD

**Issue by Goatle** [EleC0TroN/ER#7]
Description:

When using End Reborn 0.5.5 on my server / local client if you explore far enough into the End overworld biomes will start generating. In addition to this I only noticed "End Highlands" etc biomes being spawned, until the point where it started using overworld biomes. No biomes from the Endergetic Expansion were spawning.

Log:

The only thing that appeared in either logs was this line was being spammed on the server log.

`[13Jun2020 02:05:18.770] [Server-Worker-124/WARN] [net.minecraft.world.gen.layer.Layer/]: Unknown biome id: `

Solution:

For now downgrading to 0.5.4 seems to have resolved my issue. Going to test some more on my server and come back to you.

[Mod List](https://gist.github.com/Goatle/4fbf247181040729ab8b33cfdfbf5fb1)

**Comment by Goatle** [comment]
Just loaded it up on my server, can confirm that End generation is fine on version 0.5.4 and I do not receive the unkown biome id error.

**Comment by EleC0TroN** [comment]
This is strange, the mod does not affect biome generation. I’ll check now

**Comment by Goatle** [comment]
I also found it strange, was a rather lucky guess that the update caused it for me.

If you need help testing / anything additional let me know.

**Comment by EleC0TroN** [comment]
Seed: -5083369225143781511
Coordinates: 240 100 1728 and 9096 100 84
In this world it`s working
Hmm... Also You can recreate your world in creative mode and try to teleport to random points

**Comment by EleC0TroN** [comment]
Most likely this is not caused by End Reborn and The Endergetic Expansion mods. I'll try to install other mods that could affect the generation

**Comment by Goatle** [comment]
Seed: -6104795910796462377
Coordinates: 424, 60, -2512

In this world (with my attached mod list) at those exact coordinates I get a biome from the endergetic expansion, "Poise Forest" on version 0.5.4 . With version 0.5.5 of ER at that location I get a biome from the mod "Beyond the Nether Wastes", which is actually it's own dimension.

Albeit this isn't the best form of explanation.. in this picture you can see how my Journeymap updated after I had downgraded then deleted the dimension.

[Journeymap image](https://imgur.com/a/vWr2cXO)

Where I currently am is properly generated, further above (which I have not yet explored in this new End dim) is showing how the biome generation was previously.

**Comment by Goatle** [comment]
It's definitely an interaction with another mod. Upon installing Beyond the Nether Wastes, End Reborn 0.5.5, and the newest Endergetic I am not seeing this issue occur at the location. Going to boot up my full pack and see if I can replicate it on a fresh world.

**Comment by EleC0TroN** [comment]
Maybe You can use /locatebiome command (If such a team is in the modpack) to find Poise Forest in the world with [0.5.5] version

**Comment by EleC0TroN** [comment]
I now tried to run this world with the [0.5.4] and [0.5.5] version. Nothing has changed at these coordinates, but the biome is completely different
![2020-06-13_23 00 50](https://user-images.githubusercontent.com/35199902/84578023-ed54a280-adc9-11ea-8cea-2164c154707c.png)

**Comment by Goatle** [comment]
This may have just been a random bug. I cannot replicate it on a fresh world with all of my mods installed and the latest ER. I am testing using single player not a server though, not sure if that's an issue.

Going to do some more testing and see if I can figure out what caused it.

**Comment by EleC0TroN** [comment]
Okay.  I will not close this issue yet

**Comment by Goatle** [comment]
Apologies about the waste of time.

I am totally unable to replicate this after deleting that initial world (I didn't keep a backup unfortunately). Attempting using 0.5.5 and 0.5.4 on my server and local client again but am not running into generation issues.
