### ISSUE TITLE
[Bug] Enderman spawners spawn Enderman every tick

### ISSUE THREAD

**Issue by lucscood** [EleC0TroN/ER#8]
Expected Behavior:
Enderman spawners spawn Enderman at normal rates.

Enderman spawners appear to be spawning Enderman so fast it lags the game after a few seconds.

Other mods (Forge):
Optifine HD_U_G1_pre26
Phosphor 0.5.2+build.4
MixinBootstrap 1.0.3

Mod Version:
0.5.7 for 1.15.2

**Comment by EleC0TroN** [comment]
I will try to fix it soon

**Comment by EleC0TroN** [comment]
Fixed. Update will be released soon
