### ISSUE TITLE
Tag Errors

### ISSUE THREAD

**Issue by WenXin20** [EleC0TroN/ER#9]
`Minecraft v1.15.2`
`End Reborn v0.5.8`

The log is printing out quite a few tag errors related to Endorium and Ogana Fruit, provided in the link below.
[Log](https://gist.github.com/WenXin20/e540f2c00111b4922f202c9476410e6e)

**Comment by EleC0TroN** [comment]
Seems forge:mod_loaded condition does not work with tags. Okay, in the next update will be fixed

**Comment by WenXin20** [comment]
If you add an optional category and leave the values category blank, that should fix it. The optional value will only load if the item exists, so it won't print any errors if Melanism isn't installed.

Such as
```
{
  "replace": false,
  "values": [ ],
  "optional": [
    "endreborn:endorium_dust"
  ]
}

```

**Comment by EleC0TroN** [comment]
Thanks, I'll try to use this format
